apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-one
spec:
  selector:
    matchLabels:
      app: service-one
  template:
    metadata:
      labels:
        app: service-one
    spec:
      containers:
      - name: service-one
        image: sivaone/service-one:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-one
spec:
  selector:
    app: service-one
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
