spring:
  application:
    name: notebook
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/dev}
#  freemarker:
#    template-loader-path:
#      - classpath:/templates
#    suffix: .ftlh
#notebook:
#  upload-dir: C:\Users\Siva\temp