# Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - name: app
          image: sivaone/notebook:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
# Service YAML
apiVersion: v1
kind: Service
metadata:
  name: notebook
spec:
  selector:
    app: notebook
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer